---
AWSTemplateFormatVersion: 2010-09-09
Description: ECR
Parameters:
  RepositoryName:
    Type: String
Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName

Outputs:
  RepositoryName:
    Description: ECR Repository
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${RepositoryName}
    Export:
      Name: !Sub ${RepositoryName}-RepositoryName
