
name: ops-challenge-g

on:
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: run tests
      id: tests
      run: |
        go test .

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: spin-up (temp) Amazon ECR
      id: spin-up-ecr
      run: |
        ./bin/00-spin-up-ecr 

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      run: |
        ./bin/10-build-and-publish 

  deploy:
    runs-on: ubuntu-latest
    needs: [test,build]
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials for deploy
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: spin-up VPC etc and deploy
      id: spin-up-ecr
      run: |
        ./bin/11-spin-up-application-stack 
